In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('who.csv')
df.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 1 million population,Cases - newly reported in last 7 days,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 1 million population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 24 hours,Transmission Classification
0,Global,NaN,90759370,11626.410214,5110761,670774,1963169,251.484867,92305,15833,NaN
1,United States of America,Americas,22645757,68415.640000,1774844,217166,377446,1140.310000,23160,4117,Community transmission
2,India,South-East Asia,10512093,7617.430000,116815,16946,151727,109.950000,1391,198,Clusters of cases
3,Brazil,Americas,8195637,38556.920000,385237,64025,204690,962.980000,6958,1110,Community transmission
4,Russian Federation,Europe,3471053,23785.010000,162452,22850,63370,434.240000,3419,566,Clusters of cases

In [3]:
df.drop(axis=0,inplace=True,index=0)

In [4]:
df.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 1 million population,Cases - newly reported in last 7 days,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 1 million population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 24 hours,Transmission Classification
1,United States of America,Americas,22645757,68415.64,1774844,217166,377446,1140.31,23160,4117,Community transmission
2,India,South-East Asia,10512093,7617.43,116815,16946,151727,109.95,1391,198,Clusters of cases
3,Brazil,Americas,8195637,38556.92,385237,64025,204690,962.98,6958,1110,Community transmission
4,Russian Federation,Europe,3471053,23785.01,162452,22850,63370,434.24,3419,566,Clusters of cases
5,The United Kingdom,Europe,3164055,46608.35,389572,45533,83203,1225.63,6898,1243,Community transmission

In [9]:
df.reset_index(inplace=True,drop=True)

In [10]:
df.head()

,index,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 1 million population,Cases - newly reported in last 7 days,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 1 million population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 24 hours,Transmission Classification
0,1,United States of America,Americas,22645757,68415.64,1774844,217166,377446,1140.31,23160,4117,Community transmission
1,2,India,South-East Asia,10512093,7617.43,116815,16946,151727,109.95,1391,198,Clusters of cases
2,3,Brazil,Americas,8195637,38556.92,385237,64025,204690,962.98,6958,1110,Community transmission
3,4,Russian Federation,Europe,3471053,23785.01,162452,22850,63370,434.24,3419,566,Clusters of cases
4,5,The United Kingdom,Europe,3164055,46608.35,389572,45533,83203,1225.63,6898,1243,Community transmission

In [12]:
df.drop('index',axis=1,inplace=True)

In [13]:
df.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 1 million population,Cases - newly reported in last 7 days,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 1 million population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 24 hours,Transmission Classification
0,United States of America,Americas,22645757,68415.64,1774844,217166,377446,1140.31,23160,4117,Community transmission
1,India,South-East Asia,10512093,7617.43,116815,16946,151727,109.95,1391,198,Clusters of cases
2,Brazil,Americas,8195637,38556.92,385237,64025,204690,962.98,6958,1110,Community transmission
3,Russian Federation,Europe,3471053,23785.01,162452,22850,63370,434.24,3419,566,Clusters of cases
4,The United Kingdom,Europe,3164055,46608.35,389572,45533,83203,1225.63,6898,1243,Community transmission

In [14]:
df.shape

(237, 11)

In [15]:
data1=df.drop('WHO Region',axis=1)

In [16]:
data1.head()

,Name,Cases - cumulative total,Cases - cumulative total per 1 million population,Cases - newly reported in last 7 days,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 1 million population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 24 hours,Transmission Classification
0,United States of America,22645757,68415.64,1774844,217166,377446,1140.31,23160,4117,Community transmission
1,India,10512093,7617.43,116815,16946,151727,109.95,1391,198,Clusters of cases
2,Brazil,8195637,38556.92,385237,64025,204690,962.98,6958,1110,Community transmission
3,Russian Federation,3471053,23785.01,162452,22850,63370,434.24,3419,566,Clusters of cases
4,The United Kingdom,3164055,46608.35,389572,45533,83203,1225.63,6898,1243,Community transmission

In [ ]:
import seaborn as sns